insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Cougar', 1985, 'Blue', 'Mercury');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Century', 1984, 'Red', 'Buick');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('IS', 2010, 'Yellow', 'Lexus');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Spirit', 1994, 'Teal', 'Dodge');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('RDX', 2012, 'Crimson', 'Acura');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Ascender', 2006, 'Turquoise', 'Isuzu');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Econoline E150', 1999, 'Maroon', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Sierra 3500', 2010, 'Teal', 'GMC');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Continental Mark VII', 1990, 'Purple', 'Lincoln');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Allroad', 2005, 'Teal', 'Audi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Passport', 1995, 'Orange', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Discovery', 2010, 'Indigo', 'Land Rover');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Golf', 1983, 'Teal', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Outlook', 2008, 'Aquamarine', 'Saturn');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('LHS', 1999, 'Purple', 'Chrysler');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Corvette', 1973, 'Indigo', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Cabriolet', 1990, 'Indigo', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Escort', 1991, 'Puce', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Challenger', 2012, 'Pink', 'Dodge');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('LR3', 2007, 'Puce', 'Land Rover');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Express 1500', 2008, 'Indigo', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Mustang', 2004, 'Mauv', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Prius', 2010, 'Yellow', 'Toyota');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('A4', 2003, 'Maroon', 'Audi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('B-Series', 1995, 'Aquamarine', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('300', 2005, 'Goldenrod', 'Chrysler');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Metro', 1999, 'Mauv', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Bonneville', 1995, 'Khaki', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('FX', 2011, 'Khaki', 'Infiniti');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Ridgeline', 2009, 'Aquamarine', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Jetta', 2002, 'Mauv', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Park Avenue', 1992, 'Aquamarine', 'Buick');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Range Rover Sport', 2009, 'Aquamarine', 'Land Rover');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Achieva', 1998, 'Indigo', 'Oldsmobile');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Uplander', 2008, 'Indigo', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('SRX', 2010, 'Crimson', 'Cadillac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Avalon', 1997, 'Fuscia', 'Toyota');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Pajero', 2004, 'Teal', 'Mitsubishi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Montana', 2003, 'Teal', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Vision', 1994, 'Puce', 'Eagle');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Vitara', 2004, 'Fuscia', 'Suzuki');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Mark VIII', 1993, 'Green', 'Lincoln');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Sigma', 1990, 'Turquoise', 'Mitsubishi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Prelude', 2000, 'Goldenrod', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('MDX', 2006, 'Fuscia', 'Acura');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('E-Class', 1987, 'Indigo', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('E-Series', 2012, 'Purple', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Th!nk', 2000, 'Blue', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Ram Van 2500', 2003, 'Crimson', 'Dodge');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Eclipse', 1992, 'Aquamarine', 'Mitsubishi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Tahoe', 2003, 'Violet', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('626', 1999, 'Orange', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Sparrow', 2004, 'Purple', 'Corbin');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('New Beetle', 1998, 'Maroon', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('M5', 2003, 'Red', 'BMW');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Mentor', 1997, 'Puce', 'Kia');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Azera', 2006, 'Pink', 'Hyundai');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Odyssey', 2005, 'Goldenrod', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('G-Series G20', 1995, 'Red', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Escort', 1997, 'Purple', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('V70', 1998, 'Pink', 'Volvo');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Grand Am', 1997, 'Khaki', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Grand Prix', 1964, 'Goldenrod', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Shadow', 1994, 'Purple', 'Dodge');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Stealth', 1992, 'Goldenrod', 'Dodge');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Vantage', 2007, 'Violet', 'Aston Martin');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Eos', 2008, 'Mauv', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Stanza', 1992, 'Violet', 'Nissan');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('323', 1992, 'Maroon', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Echo', 2005, 'Teal', 'Toyota');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('100', 1994, 'Khaki', 'Audi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Achieva', 1995, 'Red', 'Oldsmobile');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Torrent', 2006, 'Blue', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Terrain', 2010, 'Fuscia', 'GMC');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Eclipse', 2009, 'Teal', 'Mitsubishi');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('H2', 2007, 'Mauv', 'Hummer');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('ZDX', 2010, 'Khaki', 'Acura');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Quest', 2006, 'Violet', 'Nissan');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('del Sol', 1993, 'Teal', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Uplander', 2006, 'Orange', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('New Beetle', 2006, 'Khaki', 'Volkswagen');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Tribute', 2009, 'Aquamarine', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Tribute', 2002, 'Violet', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Safari', 2002, 'Fuscia', 'GMC');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Comanche', 1992, 'Khaki', 'Jeep');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('6000', 1984, 'Crimson', 'Pontiac');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Sierra 2500', 1999, 'Violet', 'GMC');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Lynx', 1986, 'Pink', 'Mercury');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('F-Series Super Duty', 2011, 'Yellow', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Accord', 2005, 'Red', 'Honda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Scoupe', 1993, 'Maroon', 'Hyundai');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Bravada', 2000, 'Yellow', 'Oldsmobile');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('FX', 2005, 'Yellow', 'Infiniti');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Taurus', 2010, 'Turquoise', 'Ford');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Brooklands', 2010, 'Mauv', 'Bentley');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Cavalier', 1998, 'Red', 'Chevrolet');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Tucson', 2005, 'Blue', 'Hyundai');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Miata MX-5', 2005, 'Goldenrod', 'Mazda');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('CLS-Class', 2006, 'Indigo', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_year, car_color, car_company) values ('Mystique', 1996, 'Goldenrod', 'Mercury');
